#!/bin/bash
git clone https://github.com/Devil666face/Ksc15Ansible.git
cd Ksc15Ansible
wget https://github.com/Devil666face/Ksc15Ansible/releases/download/v0/ksc-web-console-15.0.136.x86_64.deb
wget https://github.com/Devil666face/Ksc15Ansible/releases/download/v0/ksc64_15.0.0-12912_amd64.deb
sudo apt update
sudo apt-get install ansible \
                sshpass \
                -y
