---
- name: Install db client
  apt:
    name:
      - "{{ 'mariadb-client' if db_type=='mysql' else 'postgresql-client' }}"
    state: present

- name: Create group kladmins
  group:
    name: kladmins

- name: Create user ksc
  user:
    name: ksc
    group: kladmins
    shell: /sbin/nologin
    create_home: no

- name: Copy ksc deb file
  copy:
    src: "./{{ksc_file_name}}"
    dest: /tmp/

- name: Create answers.txt file
  template:
    src: ./answers.txt
    dest: /tmp/answers.txt
  vars:
    ksc_ip: "{{hostvars[ 'ksc' ].ansible_default_ipv4.address}}"
    mdb_ip: "{{hostvars[ 'mdb' ].ansible_default_ipv4.address if db_type=='mysql' else hostvars[ 'psql' ].ansible_default_ipv4.address}}"
    db_port: "{{ '3306' if db_type=='mysql' else '5432' }}"

- name: Install deb file
  apt:
    deb: "/tmp/{{ksc_file_name}}"
  environment:
    KLAUTOANSWERS: /tmp/answers.txt

- name: Allow connects from mmc console
  shell: '/opt/kaspersky/ksc64/sbin/klscflag -ssvset -pv klserver -s 87 -n KLSRV_SP_SERVER_SSL_PORT_GUI_OPEN -sv true -svt BOOL_T -ss "|ss_type = \"SS_SETTINGS\";"'

- name: Restart kladminserver_srv
  systemd:
    name: kladminserver_srv
    state: restarted

- name: Get klserver.cer
  fetch:
    src: /var/opt/kaspersky/klnagent_srv/1093/cert/klserver.cer
    dest: /tmp/

- name: Wait before ksc server up
  wait_for:
    port: 13000
    delay: 40

- name: Create user for web
  shell: "/opt/kaspersky/ksc64/sbin/kladduser -n ksc -p {{ksc_web_password}}"
  ignore_errors: true
